#pragma once

#define TEXT_WINDOW_WIDTH 500
#define TEXT_WINDOW_HEIGHT 20
#define TEXT_WINDOW_PADDING_BOTTOM 100

#define EDIT_WINDOW_WIDTH 500
#define EDIT_WINDOW_HEIGHT 40
#define EDIT_WINDOW_PADDING_BOTTOM 50

#define UNLOCK_BUTTON_WIDTH 200
#define UNLOCK_BUTTON_HEIGHT 40